version: '3.9'

services:
  laravel:
    image: bitnami/laravel:latest
    container_name: laravel_app
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=my_database
      - DB_USERNAME=my_user
      - DB_PASSWORD=my_password
      # Opcional: variables de correo, clave app, etc.
    ports:
      - "80:8000"  # Puedes cambiar el puerto externo si lo necesitas
    volumes:
      - ./laravel-app:/app
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example_password
    networks:
      - my_network

networks:
  my_network:
